#!/usr/bin/env bash
# Task 5

COUNT=0
while [ $COUNT -lt 10 ]
do
    echo Best School
    COUNT=$((COUNT+1))
    if [ $COUNT -eq 4 ]
    then
        echo bad luck
    elif [ $COUNT -eq 8 ]
    then
        echo good luck
    fi
done
