#!/usr/bin/env bash
# Task 6

COUNT=0
while [ $COUNT -lt 20 ]
do
    
    case $COUNT in
    4)
        echo bad luck from China
        ;;
    
    9)
        echo bad luck from Japan
        ;;

    17)
        echo bad luck from Italy
    esac
    COUNT=$((COUNT+1))
    echo $COUNT
done
