#!/usr/bin/env bash
# Task 10

#!/usr/bin/env bash
# Task 10

echo $$ > /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit 0" SIGTERM
trap "echo 'U no love me?!'; exit 0" SIGINT
trap "rm /var/run/myscript.pid; exit 0" SIGQUIT

while true
do
    echo 'To infinity and beyond'
    sleep 2
done
