#!/usr/bin/env bash
# Task 11

if [[ $# -eq 0 ]]; then
    echo "Usage: manage_my_process {start|stop|restart}"
fi

if [[ $1 == "start" ]]; then
    echo "manage_my_process started"
    ./manage_my_process

elif [[ $1 == "stop" ]]; then
    echo "manage_my_process stopped"
    kill $(pgrep -f "manage_my_process")

elif [[ $1 == "restart" ]]; then
    echo "manage_my_process restarted"
    kill $(pgrep -f "manage_my_process")
    ./manage_my_process
fi
